export const PROJECTS_FETCH_REQUEST = 'PROJECTS_FETCH_REQUEST';
export const PROJECTS_FETCH_SUCCESS = 'PROJECTS_FETCH_SUCCESS';
export const PROJECTS_FETCH_FAIL = 'PROJECTS_FETCH_FAIL';
export const PROJECTS_RESET = 'PROJECTS_RESET';
