export const RESIZER_RESET_STATE = 'RESIZER_RESET_STATE';
export const RESIZER_CLEAR_STATE = 'RESIZER_CLEAR_STATE';

export const IMG_UPLOAD_REQUEST = 'IMG_UPLOAD_REQUEST';
export const IMG_UPLOAD_SUCCESS = 'IMG_UPLOAD_SUCCESS';
export const IMG_UPLOAD_FAIL = 'IMG_UPLOAD_FAIL';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

export const SET_IMG_FILE = 'SET_IMG_FILE';
export const SET_IMAGE_QUALITY = 'SET_IMAGE_QUALITY';
export const SET_LARGE_WIDTH = 'SET_LARGE_WIDTH';
export const SET_LARGE_HEIGHT = 'SET_LARGE_HEIGHT';
export const SET_MEDIUM_WIDTH = 'SET_MEDIUM_WIDTH';
export const SET_MEDIUM_HEIGHT = 'SET_MEDIUM_HEIGHT';
export const SET_THUMBNAIL_WIDTH = 'SET_THUMBNAIL_WIDTH';
export const SET_THUMBNAIL_HEIGHT = 'SET_THUMBNAIL_HEIGHT';
export const SET_IMAGE_SIZE = 'SET_IMAGE_SIZE';
